fix bug due to react-router v2
Error: Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.

https://github.com/expo/router/issues/740